version: "3.1"

services:
  # 1. Service: MariaDB
  db:
    image: mariadb:latest
    volumes:
      - vol-db:/var/lib/mysql
    environment:
      # Hier wird das Administratorpasswort angegeben
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root
      MYSQL_DATABASE: wp
      MYSQL_USER: wpuser
      # Hier wird das Benutzerpasswort angegeben
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_user
    # Für beide Passwörter müssen noch die entsprechenden
    # Geheimnisse angegeben werden, die später gesetzt werden
    secrets:
      - mysql_root
      - mysql_user
    restart: always
    
  # 2. Service: Wordpress
  wordpress:
    image: wordpress:latest
    volumes:
      - vol-www:/var/www/html/wp-content
    ports:
      - "8082:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_NAME: wp
      # Hier wird dasselbe Benutzerpasswort übergeben wie oben
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/mysql_user
    # Auch hier muss das entsprechende Geheimnis angegeben werden
    secrets:
      - mysql_user
    restart: always

volumes:
  vol-www:
  vol-db:

# Die oben benutzten Geheimnisse müssen hier gesetzt werden,
# wofür ihnen einfach Textdateien zugeordnet werden
secrets:
  mysql_root:
    file: ./mysql-root-pw.txt
  mysql_user:
    file: ./mysql-user-pw.txt