version: "3.1"

services:
  test:
    image: alpine
    
    # Definiert ein Geheimnis namens `password1`
    secrets:
      - password1
    # Dieses Geheimnis wird in der gleichnamigen Datei in `/run/secrets` gespeichert
    command: ["cat", "-n", "/run/secrets/password1"]

# Zudem müssen die Geheimnisse mit Inhalt gefüllt werden
secrets:
  # Für `password1` wird der Inhalt der Datei `my-secrets.txt` benutzt
  password1:
    file: ./my-secrets.txt